filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /logs/nginx/*.log
  fields:
    type: nginx
  fields_under_root: true

- type: log
  enabled: true
  paths:
    - /logs/apache/*.log
  fields:
    type: apache
  fields_under_root: true

- type: log
  enabled: true
  paths:
    - /logs/custom-web/*.log
  fields:
    type: custom-web
  fields_under_root: true

- type: container
  enabled: true
  paths:
    - /var/lib/docker/containers/*/*.log
  fields:
    type: docker
  fields_under_root: true

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644 