version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-server-v2
    ports:
      - "8080:80"
    volumes:
      - ./nginx-site:/usr/share/nginx/html:ro
      - ./logs/nginx:/var/log/nginx
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  apache:
    image: httpd:latest
    container_name: apache-server-v2
    ports:
      - "8081:80"
    volumes:
      - ./apache-site:/usr/local/apache2/htdocs:ro
      - ./logs/apache:/usr/local/apache2/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  custom-web:
    image: httpd:latest
    container_name: custom-web-v2
    ports:
      - "8082:80"
    volumes:
      - ./custom-web-site:/usr/local/apache2/htdocs:ro
      - ./logs/custom-web:/usr/local/apache2/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elasticsearch2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.1
    container_name: logstash2
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.1
    container_name: kibana2
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.12.1
    container_name: filebeat2
    user: root
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - LOGSTASH_HOSTS=http://logstash:5044
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/logs:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - elasticsearch
      - logstash
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch-data:
